version: '3.9'

services:
  app:
    build: .
    ports:
      - "8000:8000"     # FastAPI
      - "8501:8501"     # Streamlit
    volumes:
      - .:/app          # live code reload during dev (optional)
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped